/**
 * Expo config plugin: withLetsEncryptNetworkSecurity
 *
 * Why this exists
 * ---------------
 * Supabase serves its API over TLS using a Let's Encrypt certificate that
 * chains up to the "ISRG Root X1" CA. This root is trusted out-of-the-box on
 * Android 7.1+ (API 25+). On OLDER devices/emulators (Android <= 7.0) the
 * system trust store does NOT contain ISRG Root X1, which produces:
 *
 *   javax.net.ssl.SSLHandshakeException:
 *   java.security.cert.CertPathValidatorException:
 *   Trust anchor for certification path not found.
 *
 * This plugin bundles the ISRG Root X1 certificate into res/raw and wires up a
 * network_security_config.xml that trusts BOTH the system store AND that
 * bundled certificate, so the app works on old and new devices.
 *
 * IMPORTANT: This is for managed / CNG Expo projects where the `android`
 * folder is generated by `expo prebuild`. Do NOT hand-edit android/ directly,
 * those edits get wiped. Instead this plugin re-applies on every prebuild.
 *
 * Prerequisite: place the cert file at the path referenced by CERT_SOURCE
 * (default: ./android-assets/isrg_root_x1.pem). See scripts/download-isrg-cert.sh
 */

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Filename (without extension) used in res/raw -> referenced as @raw/isrg_root_x1
const CERT_RAW_NAME = 'isrg_root_x1';
// Where you keep the source cert in your project (committed to git, it's public)
const CERT_SOURCE = path.join('android-assets', `${CERT_RAW_NAME}.pem`);

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <!-- Trust everything the device/OS already trusts -->
            <certificates src="system" />
            <!-- Plus bundle Let's Encrypt ISRG Root X1 for old devices -->
            <certificates src="@raw/${CERT_RAW_NAME}" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

function withCopyCertToRaw(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const platformRoot = cfg.modRequest.platformProjectRoot; // .../android

      const srcCert = path.join(projectRoot, CERT_SOURCE);
      if (!fs.existsSync(srcCert)) {
        throw new Error(
          `[withLetsEncryptNetworkSecurity] Certificate not found at ${srcCert}.\n` +
            `Run: bash scripts/download-isrg-cert.sh  (downloads ISRG Root X1 PEM)`
        );
      }

      // 1) Copy cert into res/raw/isrg_root_x1.pem
      const rawDir = path.join(platformRoot, 'app', 'src', 'main', 'res', 'raw');
      fs.mkdirSync(rawDir, { recursive: true });
      fs.copyFileSync(srcCert, path.join(rawDir, `${CERT_RAW_NAME}.pem`));

      // 2) Write res/xml/network_security_config.xml
      const xmlDir = path.join(platformRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        NETWORK_SECURITY_CONFIG
      );

      return cfg;
    },
  ]);
}

function withManifestNetworkSecurity(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (app) {
      app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return cfg;
  });
}

module.exports = function withLetsEncryptNetworkSecurity(config) {
  config = withCopyCertToRaw(config);
  config = withManifestNetworkSecurity(config);
  return config;
};
